#!/bin/bash

modids="BCC-CSM1.1 BCC-CSM1.1 BNU-ESM CCSM4 CESM1 CESM1 CNRM-CM5  CSIRO-Mk3.6.0 CanESM2 EC-EARTH FGOALS-g2 FIO-ESM GFDL-CM3 GFDL-ESM2G GISS-E2-H GISS-E2-R HadGEM2-AO HadGEM2-ES IPSL-CM5A-LR IPSL-CM5A-MR MIROC-ESM MIROC-ESM-CHEM MIROC5 MPI-ESM-LR MPI-ESM-MR MRI-CGCM3 NorESM1-M NorESM1-ME"


for i in $modids
do
    mv *$i*.nc $i/
    ./mv_cmip5.sh ./$i
done
